// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'speech': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
